import type { Metadata } from 'next';
import './globals.css';
import { pretendard } from '@/styles/fonts';

export const metadata: Metadata = {
  title: 'Kirook',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ko' className={`${pretendard.variable}`}>
      <body className={`${pretendard.className}`}>{children}</body>
    </html>
  );
}
